### ISSUE TITLE
Serious problem

### ISSUE THREAD

**Issue by MuratGOZCU** [saaskit/saaskit#103]
**I sent my project to the server to publish and I got the following error. I'm not getting this error when I run localde. running smoothly**

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLJVE1VGSGHM", Request id "0HLJVE1VGSGHM:00000001": An unh
andled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at Sanalogi.Web.Api.CachingAppTenantResolver.ResolveAsync(HttpContext context
) in D:\SanalogiTurizmProject\Turizm_Web_Sitesi\Sanalogi\Presentation\Sanalogi.W
eb.Api\CachingAppTenantResolver.cs:line 55
   at SaasKit.Multitenancy.MemoryCacheTenantResolver`1.SaasKit.Multitenancy.ITen
antResolver<TTenant>.ResolveAsync(HttpContext context)
   at SaasKit.Multitenancy.Internal.TenantResolutionMiddleware`1.Invoke(HttpCont
ext context, ITenantResolver`1 tenantResolver)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpCo
ntext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Proces

![image](https://user-images.githubusercontent.com/31828822/51458474-51567100-1d66-11e9-9da7-eab4ef7a4d2f.png)

**Comment by Marcel0024** [comment]
It's silly if you don't publish the code. What's happening at line 55?
