### ISSUE TITLE
DI issue

### ISSUE THREAD

**Issue by dazinator** [saaskit/saaskit#42]
Hi, I read the blogs, thanks for the great library!

I am just trying to use Saaskit with my existing application, but hitting this error when a I run the application and browse to a page that has the Tenant injected:

```
Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'SaasKit.Multitenancy.TenantContext`1[Gluon.Module.Tenant.Data.TenantDomainApplication]' returned null.
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.MultitenancyServiceCollectionExtensions.<>c__0`2.<AddMultitenancy>b__0_1(IServiceProvider prov)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.<>c__DisplayClass16_0.
```

I am using Autofac.

My configure services looks like this:

```
             services.AddDbContext<AppTenantContext>(options => options.UseSqlServer(connection));         
            services.AddScoped<IAppTenantContext>(provider => provider.GetService<AppTenantContext>());

            services.AddMultitenancy<TenantDomainApplication, CachingAppTenantResolver>();

```

and Configure():

```
  app.UseMultitenancy<TenantDomainApplication>();
```

I'm then injecting the tenant into my `_Layout.cshtml`, and I get this error when I browse to a page..

**Comment by rondefreitas** [comment]
If you step through your tenantresolver, is it actually resolving a tenant?

Also, please try injecting an instance of ITenant<YourTenantClass> instead, this is designed to work even with a null tenant.

**Comment by dazinator** [comment]
I'll close this, as I switched away from autofac in the end.
