### ISSUE TITLE
TenantPipelineMiddleware

### ISSUE THREAD

**Issue by eddyjl077** [saaskit/saaskit#44]
**This is an error that appear multiple time in my log.**

System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.<CopyToAsync>d1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.StaticFiles.StaticFileContext.<SendRangeAsync>d47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SaasKit.Multitenancy.Internal.TenantPipelineMiddleware1.<Invoke>d__5.MoveNext() in C:\Users\eddy\Documents\eddy\src\SaasKit.Multitenancy\Internal\TenantPipelineMiddleware.cs:line 44 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at SaasKit.Multitenancy.Internal.TenantResolutionMiddleware1.<Invoke>d3.MoveNext() in C:\Users\eddy\Documents\eddy\src\SaasKit.Multitenancy\Internal\TenantResolutionMiddleware.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

**Comment by benfoster** [comment]
I'm not able to replicate this. If you're still experiencing this issue, please post more details of your application setup.
