### ISSUE TITLE
Trying to get started with SaasKit but...

### ISSUE THREAD

**Issue by sheilaqf** [saaskit/saaskit#47]
Hello,
I'm implementing (or at least trying to implement) my first multi-tenant app using SaasKit by following the post in http://benfoster.io/blog/asp-net-5-multitenancy "Building multi-tenant applications with ASP.NET Core (ASP.NET 5)". But when I open up cmd prompt and type dnx . web I get:

D:\saaskit-master\Multi-Tenant_Demo>dnx . web
System.InvalidOperationException: Failed to resolve the following dependencies f
or target framework 'DNXCore,Version=v5.0':
   EntityFramework.Commands 7.0.0-beta5
   EntityFramework.SqlServer 7.0.0-beta5
   Microsoft.AspNet.Authentication.Cookies 1.0.0-beta5
   Microsoft.AspNet.Authentication.Facebook 1.0.0-beta5
   Microsoft.AspNet.Authentication.Google 1.0.0-beta5
   Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta5
   Microsoft.AspNet.Authentication.Twitter 1.0.0-beta5
   Microsoft.AspNet.Diagnostics 1.0.0-beta5
   Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta5
   Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta5
   Microsoft.AspNet.Mvc 6.0.0-beta5
   Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta5
   Microsoft.AspNet.Server.IIS 1.0.0-beta5
   Microsoft.AspNet.Server.WebListener 1.0.0-beta5
   Microsoft.AspNet.StaticFiles 1.0.0-beta5
   Microsoft.AspNet.Tooling.Razor 1.0.0-beta5
   Microsoft.AspNetCore.Http 1.0.0
   Microsoft.AspNetCore.Http.Abstractions 1.0.0
   Microsoft.AspNetCore.Http.Extensions 1.0.0
   Microsoft.Extensions.Caching.Abstractions 1.0.0
   Microsoft.Extensions.Caching.Memory 1.0.0
   Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0
   Microsoft.Extensions.Logging.Abstractions 1.0.0
   Microsoft.Framework.Configuration.Abstractions 1.0.0-beta5
   Microsoft.Framework.Configuration.Json 1.0.0-beta5
   Microsoft.Framework.Configuration.UserSecrets 1.0.0-beta5
   Microsoft.Framework.Logging 1.0.0-beta5
   Microsoft.Framework.Logging.Console 1.0.0-beta5
   Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0-beta5
   NETStandard.Library 1.6.0
   SaasKit.Multitenancy 1.1.4

Searched Locations:
  D:\TostoneT\saaskit-master{name}\project.json
  D:\TostoneT\saaskit-master\src{name}\project.json
  D:\TostoneT\saaskit-master\test{name}\project.json

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationNa
me)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly ass
embly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)

How can I resolve this issue?

**Comment by luisrudge** [comment]
`dnx` and `dnu` doesn't exist anymore. Download the latest bits and try again https://www.microsoft.com/net/download

**Comment by sheilaqf** [comment]
@luisrudge I'm now updating my VS2015 to VS2015.3. Do you thing by doing this I need yet to download all those things at https://www.microsoft.com/net/download?

**Comment by luisrudge** [comment]
VS will ask you to download as well

**Comment by sheilaqf** [comment]
Then, those are all the things VS will install during VS2015.3 setup?

**Comment by sheilaqf** [comment]
I want to be sure that having this last version of VS, I have all I need to built my first Multi-tenant app.

**Comment by luisrudge** [comment]
VS will ask you to download the .net core VS tooling, which you can find here: https://go.microsoft.com/fwlink/?LinkId=827546

**Comment by sheilaqf** [comment]
OK. I'm downloading it right now. I hope this two things (VS2015.3 & .NET Core) are all I need to finally starting.

**Comment by papyr** [comment]
The latest dependencies do not fully resolve in VS 2015, I created a ticket hopefully to get a working build with [the latest nugets updated](https://github.com/saaskit/saaskit/issues/59)
